version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3001:3000'
    volumes: 
      - '.:/product-test'
    environment:
      - 'DATABASE_PASSWORD='
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db


  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
